### ISSUE TITLE
Raidframes position keeps reseting.

### ISSUE THREAD

**Issue by Teknishun7** [luskanek/CRAP#7]
Im not sure if it's because I updated CRF to CRAP, but since the update the raidframes position keeps resetting every time I log on a character. Not exactly sure how to fix this. It's like it's retaining the old value it had with CRF. I never ALT-F4 and I always wait the full timer to logout so my addons always save their config properly.

Nothing game breaking but I have to drag it back every time I log back in.

**Comment by Teknishun7** [comment]
I cant reproduce. Maybe I'm crazy or it was just a fluke. Sorry for bothering if I can diagnose something concrete I'll reopen the issue.

**Comment by luskanek** [comment]
Let me know if it happens again but I've failed to reproduce it myself.

**Comment by Teknishun7** [comment]
I couldn't explain by what voodoo magic this happens but rebooting the PC seems to replicate the behavior.

Was here last time I played yesterday:
![image](https://github.com/luskanek/CRAP/assets/89323351/9b73b55a-c5e8-493f-b2be-5b37efb5dc20)

Now its reset back here:
![image](https://github.com/luskanek/CRAP/assets/89323351/dfd056f5-2c1a-45b4-aa0f-13512c8100fe)

So I wasn't crazy, but I really don't know how this could happen lol.

Same for my GF PC so it happened on two of my machines/account.

Feel free to close the issue if you can't figure it out tho its not like its a major bug or anything and its really just the position that resets the other setting like class color doesnt reset.

*shrugs*

**Comment by luskanek** [comment]
That's weird, that definitely should not happen. I'll see if I can find the problem and try to fix it.

**Comment by luskanek** [comment]
I am not able to reproduce this no matter what. The frame always stays wherever I drag it to. After you move the frame and quit the client, check the layout-cache.txt at <game-folder>/WTF/Account/<account>/<realm-name>/<character-name>. It should contain the 'GroupFrame' along with its screen coordinates. Another thing to check is if your game folder is read-only, that may cause issues too.

**Comment by Teknishun7** [comment]
It only happens when I reboot the machine. The files are also not write protected. Im able to modfy other config and it always sticks, its also only the position that resets the other setting like no class color sticks (see screenshots above). To be honest Im as confused as you are. Im suspecting voodoo magic at this point and again its just a slight anoyance nothing major.

Thanks for looking it up. Lets just close the issue and if I find what was causing it I'll repost here.

**Comment by luskanek** [comment]
@Teknishun7 hopefully fixed with fd0c061. The position is now saved manually instead of relying on the built-in system. Better to be safe than sorry :)
